function Hd = bandpass_filter(Fs, Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, Astop2, match)
%BANDPASS_FILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 30-Aug-2024 14:58:28

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 500;  % Sampling Frequency
% 
% Fstop1 = 20;          % First Stopband Frequency
% Fpass1 = 30;          % First Passband Frequency
% Fpass2 = 200;         % Second Passband Frequency
% Fstop2 = 250;         % Second Stopband Frequency
% Astop1 = 60;          % First Stopband Attenuation (dB)
% Apass  = 1;           % Passband Ripple (dB)
% Astop2 = 80;          % Second Stopband Attenuation (dB)
% match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
